#JPQL
CentroCostos.findByCodigoNamedFile = select c from CentroCostos c where c.codigo=?1
CentroCostos.findAllNamedFile = select c from CentroCostos c order by c.codigo desc
CentroCostos.sampleNamedQuery = select LENGTH(c.nombre) from CentroCostos c where c.codigo = :codigo

#SQL Nativo
CentroCostos.findAllNamedNativeFile = select * from sh_empresa_20441636831.tb_at_centrocostos order by tb_centrocostos_cod DESC
CentroCostos.sampleNamedNativeQuery= select LENGTH(tb_centrocostos_nom) from sh_empresa_20441636831.tb_at_centrocostos where tb_centrocostos_cod=:codigo 
